name: CI

on:
  push:
    branches: ["codex/quality-pass"]
  pull_request:

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Ruff
        run: ruff check app.py server/api server/config.py server/utils/logging.py
      - name: Pyright
        run: pyright
      - name: Pytest
        run: pytest
